server:
  port: 8081
  servlet:
    context-path: /springboot-grpc-server
spring:
  application:
    name: springboot-grpc-server
grpc:
  server:
    port: 9898

# 网关配置
gateway:
  url: http://localhost:8080  # 网关地址
  service-name: ${spring.application.name}
  port: ${server.port}
  ip: 127.0.0.1  # 强制使用localhost
  health-path: /actuator/health
  description: "gRPC服务"
  version: "1.0.0"

# 健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

